### ISSUE TITLE
-bash: magnet-to-ipfs: command not found

### ISSUE THREAD

**Issue by mushokumunou** [VictorBjelkholm/magnet-to-ipfs#1]
-bash: magnet-to-ipfs: command not found
[11]-  Done                    tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce
[12]+  Done                    tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969%2Fannounce

How to fix this error?

**Comment by victorb** [comment]
You need to wrap the magnet link in `"` (quotes). See the example in the readme:

```
magnet-to-ipfs "magnet:?xt=urn:btih:08ada5a7a6183aae1e09d831df6748d566095a10&dn=Sintel&tr=udp%3A%2F%2Fexplodie.org%3A6969&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969&tr=udp%3A%2F%2Ftracker.empire-js.us%3A1337&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337&tr=wss%3A%2F%2Ftracker.btorrent.xyz&tr=wss%3A%2F%2Ftracker.fastcast.nz&tr=wss%3A%2F%2Ftracker.openwebtorrent.com&ws=https%3A%2F%2Fwebtorrent.io%2Ftorrents%2F&xs=https%3A%2F%2Fwebtorrent.io%2Ftorrents%2Fsintel.torrent"
```

**Comment by mushokumunou** [comment]
Thank you for a reply.
Here is my installation logs for a reference .
[log.txt](https://github.com/VictorBjelkholm/magnet-to-ipfs/files/1756834/log.txt)

**Comment by mushokumunou** [comment]
Thank you for your quick reply.
Resolved.
